name: blog

dependencies:
  - base >= 4.7 && < 5
  - hakyll == 4.14.1.0
  - containers
  - binary
  - text ^>= 1.2.4.1
  - time-locale-compat
  - time
  - pandoc
  - pandoc-types ^>= 1.22
  - JuicyPixels ^>= 3.3.5
  - safe-exceptions ^>= 0.1.7.2
  - filepath ^>= 1.4.2.1
  - temporary ^>= 1.3
  - transformers ^>= 0.5.6.2
  - process ^>= 1.6.13.2
  - directory ^>= 1.3.6.0
  - base64-bytestring ^>= 1.1.0.0
  - bytestring ^>= 0.10.12.0
  - extra ^>= 1.7.9

library:
  source-dirs: src
  other-modules: []

executables:
  blog:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - blog
    other-modules: []

